"""First

Revision ID: 17c4fa20f0d3
Revises: 
Create Date: 2022-03-12 14:11:23.858681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c4fa20f0d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_leader', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('work_size', sa.Integer(), nullable=True),
    sa.Column('collaborators', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
